# Generated by Django 3.2.22 on 2023-10-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='region',
            field=models.CharField(max_length=30),
        ),
    ]
