# Generated by Django 3.2.22 on 2023-10-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_auto_20231023_1410'),
        ('clients', '0002_auto_20231010_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='client_type_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='enterprise',
            new_name='enterprise_id',
        ),
        migrations.AddField(
            model_name='clienttype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='enterprise_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(max_length=30),
        ),
    ]
