# Generated by Django 3.2.22 on 2023-10-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dtes', '0001_initial'),
        ('enterprises', '0002_auto_20231023_1410'),
        ('clients', '0004_auto_20231023_1414'),
        ('items', '0004_auto_20231023_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('date', models.DateField()),
                ('net_total', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('dte_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtes.dtetype')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.sell')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSellReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('date', models.DateField()),
                ('dte_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtes.dtetype')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.sell')),
            ],
        ),
    ]
